name: Angel's enviroment

on:
  push:
    branches: [ angelDev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        USER_DB: ${{ secrets.USER_DB }}
        PASS_DB: ${{ secrets.PASS_DB }}
    - name: Deploy in Tomcat
      run: mvn tomcat7:redeploy
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        USER_DB: ${{ secrets.USER_DB }}
        PASS_DB: ${{ secrets.PASS_DB }}
