name: DataBase devellopment enviroment

on:
  push:
    branches: [ db_dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        USER_DB: ${{ secrets.USER_DB }}
        PASS_DB: ${{ secrets.PASS_DB }}
    - name: Run Migration FlywayDB
      run: mvn flyway:repair flyway:migrate
      env:
        USER_DB: ${{ secrets.USER_DB }}
        PASS_DB: ${{ secrets.PASS_DB }}
